# Generated by Django 5.0.3 on 2024-03-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('total_years_of_experience', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'db_table': 'admin_therapist',
                'ordering': ('name',),
            },
        ),
    ]
