# Generated by Django 5.0.3 on 2024-03-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ('therapist_id',), 'verbose_name': 'Therapist', 'verbose_name_plural': 'Therapists'},
        ),
    ]
