# Generated by Django 5.0.3 on 2024-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0002_alter_therapist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('posted_problems', models.IntegerField()),
                ('last_posted_problem', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'admin_case',
                'ordering': ('case_id',),
            },
        ),
    ]
