# Generated by Django 5.0.3 on 2024-03-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0005_rename_locatoin_therapist_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contact_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='joined_from',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='mail_id',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='total_problems_posted',
            field=models.IntegerField(null=True),
        ),
    ]
