# Generated by Django 5.0.3 on 2024-03-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0006_case_contact_number_case_joined_from_case_mail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='last_posted_problem',
        ),
    ]
