# Generated by Django 5.0.3 on 2024-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0010_case_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='mail_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='total_solutions_posted',
        ),
        migrations.AddField(
            model_name='therapist',
            name='request_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='case',
            table='chief_case',
        ),
        migrations.AlterModelTable(
            name='problem',
            table='chief_problem',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='chief_solution',
        ),
        migrations.AlterModelTable(
            name='therapist',
            table='chief_therapist',
        ),
    ]
