# Generated by Django 5.0.3 on 2024-03-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0011_rename_mail_id_therapist_email_and_more'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Patient',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('case_id',), 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='chief_patient',
        ),
    ]
