# Generated by Django 5.0.3 on 2024-03-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0013_alter_problem_options_rename_mail_id_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='chief.problem'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chief.therapist'),
        ),
    ]
