# Generated by Django 5.0.3 on 2024-03-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0016_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='joined_from',
            field=models.DateTimeField(max_length=100),
        ),
    ]
