# Generated by Django 5.0.3 on 2024-03-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0017_alter_therapist_joined_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
