# Generated by Django 5.0.3 on 2024-03-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0018_alter_patient_password_alter_therapist_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_posted_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_posted_for_patient', to='chief.problem'),
        ),
    ]
