# Generated by Django 5.0.3 on 2024-03-20 10:48

import chief.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0020_alter_therapist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to=chief.models.get_therapist_idproof_file_path),
        ),
        migrations.AddField(
            model_name='therapist',
            name='qualification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
