# Generated by Django 5.0.3 on 2024-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0021_therapist_id_proof_therapist_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date_added',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
