# Generated by Django 5.0.3 on 2024-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0022_solution_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
