# Generated by Django 5.0.3 on 2024-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chief', '0023_therapist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
